name: rigofunc - xyting's blog
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
paginate: 5
github: https://www.github.com/xyting
urls:
    - text: love.net
      url: https://github.com/lovedotnet
    - text: email
      url: mailto:rigofunc@outlook.com