name: RigoFunc - xyting's blog
markdown: redcarpet
highlighter: pygments
paginate: 5
github: https://www.github.com/xyting
urls:
    - text: github
      url: https://github.com/xyting
    - text: email
      url: mailto:wo@xyting.org