name: RigoFunc
desc: xyting's blog
markdown: redcarpet
highlighter: pygments
github: https://www.github.com/xyting
about: I am an independent developer from the sunny UK. I dabble in Ruby, play in C and I'm an avid systems administrator.
urls:
    - text: github
      url: https://github.com/xyting
    - text: email
      url: mailto:wo@xyting.org