name: rigofunc - xyting's blog
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
paginate: 5
github: https://www.github.com/xyting
urls:
    - text: Arch
      url: https://github.com/Arch
    - text: email
      url: mailto:rigofunc@outlook.com
