name: RigoFunc - xyting's blog
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
paginate: 5
github: https://www.github.com/xyting
urls:
    - text: github
      url: https://github.com/xyting
    - text: email
      url: mailto:wo@xyting.org